<?php
include("sesion.php");
	$pagina='insert909PHP';
	include("seguridadForm.php");
include("sql/insertFormulario.php");

if (isset($_POST['insertar'])){
	if (isset($idobra)){
  $obra = mysqli_query($conexion,"SELECT parcela,subparcela FROM obras WHERE codObra = '$idobra'");
  $ob = mysqli_fetch_array($obra);
  $sqlF909 = insertForm909(
  $ob['parcela'],
  $ob['subparcela'],
  $_POST['OliHect1'],
  $_POST['OliArea1'],
  $_POST['OliCa1'],
  (isset($_POST['OliPre1']) ? true : false),
  (isset($_POST['OliPro1']) ? true : false),
  (isset($_POST['OliPos1']) ? true : false),
  $_POST['OliHect2'],
  $_POST['OliArea2'],
  $_POST['OliCa2'],
  (isset($_POST['OliPre2']) ? true : false),
  (isset($_POST['OliPro2']) ? true : false),
  (isset($_POST['OliPos2']) ? true : false),
  $_POST['OliHect3'],
  $_POST['OliArea3'],
  $_POST['OliCa3'],
  (isset($_POST['OliPre3']) ? true : false),
  (isset($_POST['OliPro3']) ? true : false),
  (isset($_POST['OliPos3']) ? true : false),
  $_POST['OliHect4'],
  $_POST['OliArea4'],
  $_POST['OliCa4'],
  (isset($_POST['OliPre4']) ? true : false),
  (isset($_POST['OliPro4']) ? true : false),
  (isset($_POST['OliPos4']) ? true : false),
  $_POST['OliHect5'],
  $_POST['OliArea5'],
  $_POST['OliCa5'],
  (isset($_POST['OliPre5']) ? true : false),
  (isset($_POST['OliPro5']) ? true : false),
  (isset($_POST['OliPos5']) ? true : false),
  $_POST['OliHect6'],
  $_POST['OliArea6'],
  $_POST['OliCa6'],
  (isset($_POST['OliPre6']) ? true : false),
  (isset($_POST['OliPro6']) ? true : false),
  (isset($_POST['OliPos6']) ? true : false),
  $_POST['OliHect7'],
  $_POST['OliArea7'],
  $_POST['OliCa7'],
  (isset($_POST['OliPre7']) ? true : false),
  (isset($_POST['OliPro7']) ? true : false),
  (isset($_POST['OliPos7']) ? true : false),
	$_POST['OliCa8'],
  $_POST['OliHect8'],
  $_POST['OliArea8'],
  (isset($_POST['OliPre8']) ? true : false),
  (isset($_POST['OliPro8']) ? true : false),
  (isset($_POST['OliPos8']) ? true : false),
  $_POST['OliHect9'],
  $_POST['OliArea9'],
  $_POST['OliCa9'],
  (isset($_POST['OliPre9']) ? true : false),
  (isset($_POST['OliPro9']) ? true : false),
  (isset($_POST['OliPos9']) ? true : false),
  $_POST['FruDet1'],
  $_POST['FruEst1'],
  $_POST['FruHect1'],
  $_POST['FruArea1'],
  $_POST['FruCa1'],
  (isset($_POST['FruPre1']) ? true : false),
  (isset($_POST['FruPro1']) ? true : false),
  (isset($_POST['FruePos1']) ? true : false),
  $_POST['FruDet2'],
  $_POST['FruEst2'],
  $_POST['FruHect2'],
  $_POST['FruArea2'],
  $_POST['FruCa2'],
  (isset($_POST['FruPre2']) ? true : false),
  (isset($_POST['FruPro2']) ? true : false),
  (isset($_POST['FruPos2']) ? true : false),
  $_POST['FruDet3'],
  $_POST['FruEst3'],
  $_POST['FruHect3'],
	$_POST['FruArea3'],
  $_POST['FruCa3'],
  (isset($_POST['FruPre3']) ? true : false),
  (isset($_POST['FruPro3']) ? true : false),
  (isset($_POST['FruPos3']) ? true : false),
  $_POST['FruDet4'],
  $_POST['FruEst4'],
	$_POST['FruHect4'],
  $_POST['FruArea4'],
  $_POST['FruCa4'],
  (isset($_POST['FruPre4']) ? true : false),
  (isset($_POST['FruPro4']) ? true : false),
  (isset($_POST['FruPos4']) ? true : false),
  $_POST['FruDet5'],
  $_POST['FruEst5'],
  $_POST['FruHect5'],
  $_POST['FruArea5'],
  $_POST['FruCa5'],
  (isset($_POST['FruPre5']) ? true : false),
  (isset($_POST['FruPro5']) ? true : false),
  (isset($_POST['FruPos5']) ? true : false),
  $_POST['FruDet6'],
  $_POST['FruEst6'],
  $_POST['FruHect6'],
  $_POST['FruArea6'],
  $_POST['FruCa6'],
  (isset($_POST['FruPre6']) ? true : false),
  (isset($_POST['FruPro6']) ? true : false),
  (isset($_POST['FruPos6']) ? true : false),
  $_POST['FruDet7'],
  $_POST['FruEst7'],
  $_POST['FruHect7'],
  $_POST['FruArea7'],
  $_POST['FruCa7'],
  (isset($_POST['FruPre7']) ? true : false),
  (isset($_POST['FruPro7']) ? true : false),
  (isset($_POST['FruPos7']) ? true : false),
  $_POST['FruDet8'],
  $_POST['FruEst8'],
  $_POST['FruHect8'],
  $_POST['FruArea8'],
  $_POST['FruCa8'],
  (isset($_POST['FruPre8']) ? true : false),
  (isset($_POST['FruPro8']) ? true : false),
  (isset($_POST['FruPos8']) ? true : false),
  $_POST['FruDet9'],
  $_POST['FruEst9'],
  $_POST['FruHect9'],
  $_POST['FruArea9'],
  $_POST['FruCa9'],
  (isset($_POST['FruPre9']) ? true : false),
  (isset($_POST['FruPro9']) ? true : false),
  (isset($_POST['FruPos9']) ? true : false),
  $_POST['PlanDet1'],
  $_POST['PlanEst1'],
  $_POST['PlanHect1'],
	$_POST['PlanArea1'],
  $_POST['PlanCa1'],
  (isset($_POST['PlanPre1']) ? true : false),
  (isset($_POST['PlanPro1']) ? true : false),
  $_POST['PlanDet2'],
  $_POST['PlanEst2'],
  $_POST['PlanHect2'],
  $_POST['PlanArea2'],
  $_POST['PlanCa2'],
  (isset($_POST['PlanPre2']) ? true : false),
  (isset($_POST['PlanPro2']) ? true : false),
  $_POST['PlanDet3'],
  $_POST['PlanEst3'],
  $_POST['PlanHect3'],
  $_POST['PlanArea3'],
  $_POST['PlanCa3'],
  (isset($_POST['PlanPre3']) ? true : false),
  (isset($_POST['PlanPro3']) ? true : false),
  $_POST['PlanDet4'],
  $_POST['PlanEst4'],
	$_POST['PlanHect4'],
  $_POST['PlanArea4'],
  $_POST['PlanCa4'],
  (isset($_POST['PlanPre4']) ? true : false),
  (isset($_POST['PlanPro4']) ? true : false),
  $_POST['PlanDet5'],
  $_POST['PlanEst5'],
  $_POST['PlanHect5'],
  $_POST['PlanArea5'],
  $_POST['PlanCa5'],
  (isset($_POST['PlanPre5']) ? true : false),
  (isset($_POST['PlanPro5']) ? true : false),
	$_POST['PlanDet6'],
  $_POST['PlanEst6'],
	$_POST['PlanHect6'],
  $_POST['PlanArea6'],
  $_POST['PlanCa6'],
  (isset($_POST['PlanPre6']) ? true : false),
  (isset($_POST['PlanPro6']) ? true : false),
  $_POST['PlanDet7'],
  $_POST['PlanEst7'],
  $_POST['PlanHect7'],
  $_POST['PlanArea7'],
  $_POST['PlanCa7'],
  (isset($_POST['PlanPre7']) ? true : false),
  (isset($_POST['PlanPro7']) ? true : false),
  $_POST['PlanDet8'],
  $_POST['PlanEst8'],
  $_POST['PlanHect8'],
  $_POST['PlanArea8'],
  $_POST['PlanCa8'],
  (isset($_POST['PlanPre8']) ? true : false),
  (isset($_POST['PlanPro8']) ? true : false),
  $_POST['PlanDet9'],
  $_POST['PlanEst9'],
  $_POST['PlanHect9'],
  $_POST['PlanArea9'],
  $_POST['PlanCa9'],
  (isset($_POST['PlanPre9']) ? true : false),
  (isset($_POST['PlanPro9']) ? true : false),
	$_POST['mostrarProf']);

  include("sql/sqlconnection.php");

  if($dbStatus != "Exitosa")
    exit($dbStatus);

		try {
			// use exec() because no results are returned
			$conn->exec($sqlF909);
			$lastID = $conn->lastInsertId();
			$queryCount = "SELECT MAX(version) AS cuenta FROM `cedulaformularios` WHERE nroFormulario = 909 AND idCedula = $Cedula";
			$count = $conn->query($queryCount)->fetch();
			$version = ((int)$count["cuenta"]) + 1;
			$queryObra = "INSERT INTO cedulaformularios
			(idCedulaFormularios, idCedula, tipoCedula, nroFormulario, `version`, `data`, codForm)
			VALUES (default, $Cedula, $TipoDeCedula, 909, $version, YEAR(CURDATE()), $lastID)";
			$conn->exec($queryObra);
			} catch(PDOException $e) {
			echo "Fallo el registro:" . $e->getMessage();
			}
		}else{
				$sql = updateForm909($idform,
				$_POST['OliHect1'],
			  $_POST['OliArea1'],
			  $_POST['OliCa1'],
			  (isset($_POST['OliPre1']) ? true : false),
			  (isset($_POST['OliPro1']) ? true : false),
			  (isset($_POST['OliPos1']) ? true : false),
			  $_POST['OliHect2'],
			  $_POST['OliArea2'],
			  $_POST['OliCa2'],
			  (isset($_POST['OliPre2']) ? true : false),
			  (isset($_POST['OliPro2']) ? true : false),
			  (isset($_POST['OliPos2']) ? true : false),
			  $_POST['OliHect3'],
			  $_POST['OliArea3'],
			  $_POST['OliCa3'],
			  (isset($_POST['OliPre3']) ? true : false),
			  (isset($_POST['OliPro3']) ? true : false),
			  (isset($_POST['OliPos3']) ? true : false),
			  $_POST['OliHect4'],
			  $_POST['OliArea4'],
			  $_POST['OliCa4'],
			  (isset($_POST['OliPre4']) ? true : false),
			  (isset($_POST['OliPro4']) ? true : false),
			  (isset($_POST['OliPos4']) ? true : false),
			  $_POST['OliHect5'],
			  $_POST['OliArea5'],
			  $_POST['OliCa5'],
			  (isset($_POST['OliPre5']) ? true : false),
			  (isset($_POST['OliPro5']) ? true : false),
			  (isset($_POST['OliPos5']) ? true : false),
			  $_POST['OliHect6'],
			  $_POST['OliArea6'],
			  $_POST['OliCa6'],
			  (isset($_POST['OliPre6']) ? true : false),
			  (isset($_POST['OliPro6']) ? true : false),
			  (isset($_POST['OliPos6']) ? true : false),
			  $_POST['OliHect7'],
			  $_POST['OliArea7'],
			  $_POST['OliCa7'],
			  (isset($_POST['OliPre7']) ? true : false),
			  (isset($_POST['OliPro7']) ? true : false),
			  (isset($_POST['OliPos7']) ? true : false),
				$_POST['OliCa8'],
			  $_POST['OliHect8'],
			  $_POST['OliArea8'],
			  (isset($_POST['OliPre8']) ? true : false),
			  (isset($_POST['OliPro8']) ? true : false),
			  (isset($_POST['OliPos8']) ? true : false),
			  $_POST['OliHect9'],
			  $_POST['OliArea9'],
			  $_POST['OliCa9'],
			  (isset($_POST['OliPre9']) ? true : false),
			  (isset($_POST['OliPro9']) ? true : false),
			  (isset($_POST['OliPos9']) ? true : false),
			  $_POST['FruDet1'],
			  $_POST['FruEst1'],
			  $_POST['FruHect1'],
			  $_POST['FruArea1'],
			  $_POST['FruCa1'],
			  (isset($_POST['FruPre1']) ? true : false),
			  (isset($_POST['FruPro1']) ? true : false),
			  (isset($_POST['FruePos1']) ? true : false),
			  $_POST['FruDet2'],
			  $_POST['FruEst2'],
			  $_POST['FruHect2'],
			  $_POST['FruArea2'],
			  $_POST['FruCa2'],
			  (isset($_POST['FruPre2']) ? true : false),
			  (isset($_POST['FruPro2']) ? true : false),
			  (isset($_POST['FruPos2']) ? true : false),
			  $_POST['FruDet3'],
			  $_POST['FruEst3'],
			  $_POST['FruHect3'],
				$_POST['FruArea3'],
			  $_POST['FruCa3'],
			  (isset($_POST['FruPre3']) ? true : false),
			  (isset($_POST['FruPro3']) ? true : false),
			  (isset($_POST['FruPos3']) ? true : false),
			  $_POST['FruDet4'],
			  $_POST['FruEst4'],
				$_POST['FruHect4'],
			  $_POST['FruArea4'],
			  $_POST['FruCa4'],
			  (isset($_POST['FruPre4']) ? true : false),
			  (isset($_POST['FruPro4']) ? true : false),
			  (isset($_POST['FruPos4']) ? true : false),
			  $_POST['FruDet5'],
			  $_POST['FruEst5'],
			  $_POST['FruHect5'],
			  $_POST['FruArea5'],
			  $_POST['FruCa5'],
			  (isset($_POST['FruPre5']) ? true : false),
			  (isset($_POST['FruPro5']) ? true : false),
			  (isset($_POST['FruPos5']) ? true : false),
			  $_POST['FruDet6'],
			  $_POST['FruEst6'],
			  $_POST['FruHect6'],
			  $_POST['FruArea6'],
			  $_POST['FruCa6'],
			  (isset($_POST['FruPre6']) ? true : false),
			  (isset($_POST['FruPro6']) ? true : false),
			  (isset($_POST['FruPos6']) ? true : false),
			  $_POST['FruDet7'],
			  $_POST['FruEst7'],
			  $_POST['FruHect7'],
			  $_POST['FruArea7'],
			  $_POST['FruCa7'],
			  (isset($_POST['FruPre7']) ? true : false),
			  (isset($_POST['FruPro7']) ? true : false),
			  (isset($_POST['FruPos7']) ? true : false),
			  $_POST['FruDet8'],
			  $_POST['FruEst8'],
			  $_POST['FruHect8'],
			  $_POST['FruArea8'],
			  $_POST['FruCa8'],
			  (isset($_POST['FruPre8']) ? true : false),
			  (isset($_POST['FruPro8']) ? true : false),
			  (isset($_POST['FruPos8']) ? true : false),
			  $_POST['FruDet9'],
			  $_POST['FruEst9'],
			  $_POST['FruHect9'],
			  $_POST['FruArea9'],
			  $_POST['FruCa9'],
			  (isset($_POST['FruPre9']) ? true : false),
			  (isset($_POST['FruPro9']) ? true : false),
			  (isset($_POST['FruPos9']) ? true : false),
			  $_POST['PlanDet1'],
			  $_POST['PlanEst1'],
			  $_POST['PlanHect1'],
				$_POST['PlanArea1'],
			  $_POST['PlanCa1'],
			  (isset($_POST['PlanPre1']) ? true : false),
			  (isset($_POST['PlanPro1']) ? true : false),
			  $_POST['PlanDet2'],
			  $_POST['PlanEst2'],
			  $_POST['PlanHect2'],
			  $_POST['PlanArea2'],
			  $_POST['PlanCa2'],
			  (isset($_POST['PlanPre2']) ? true : false),
			  (isset($_POST['PlanPro2']) ? true : false),
			  $_POST['PlanDet3'],
			  $_POST['PlanEst3'],
			  $_POST['PlanHect3'],
			  $_POST['PlanArea3'],
			  $_POST['PlanCa3'],
			  (isset($_POST['PlanPre3']) ? true : false),
			  (isset($_POST['PlanPro3']) ? true : false),
			  $_POST['PlanDet4'],
			  $_POST['PlanEst4'],
				$_POST['PlanHect4'],
			  $_POST['PlanArea4'],
			  $_POST['PlanCa4'],
			  (isset($_POST['PlanPre4']) ? true : false),
			  (isset($_POST['PlanPro4']) ? true : false),
			  $_POST['PlanDet5'],
			  $_POST['PlanEst5'],
			  $_POST['PlanHect5'],
			  $_POST['PlanArea5'],
			  $_POST['PlanCa5'],
			  (isset($_POST['PlanPre5']) ? true : false),
			  (isset($_POST['PlanPro5']) ? true : false),
				$_POST['PlanDet6'],
			  $_POST['PlanEst6'],
				$_POST['PlanHect6'],
			  $_POST['PlanArea6'],
			  $_POST['PlanCa6'],
			  (isset($_POST['PlanPre6']) ? true : false),
			  (isset($_POST['PlanPro6']) ? true : false),
			  $_POST['PlanDet7'],
			  $_POST['PlanEst7'],
			  $_POST['PlanHect7'],
			  $_POST['PlanArea7'],
			  $_POST['PlanCa7'],
			  (isset($_POST['PlanPre7']) ? true : false),
			  (isset($_POST['PlanPro7']) ? true : false),
			  $_POST['PlanDet8'],
			  $_POST['PlanEst8'],
			  $_POST['PlanHect8'],
			  $_POST['PlanArea8'],
			  $_POST['PlanCa8'],
			  (isset($_POST['PlanPre8']) ? true : false),
			  (isset($_POST['PlanPro8']) ? true : false),
			  $_POST['PlanDet9'],
			  $_POST['PlanEst9'],
			  $_POST['PlanHect9'],
			  $_POST['PlanArea9'],
			  $_POST['PlanCa9'],
			  (isset($_POST['PlanPre9']) ? true : false),
			  (isset($_POST['PlanPro9']) ? true : false),
				$_POST['mostrarProf']);

				mysqli_query($conexion,$sql)or die("Problemas en la actualizacion".mysqli_error($conexion));
			}

		$conn = null;
		echo "<script language='javascript'>";
		echo "alert('El formulario 909 se cargo correctamente');";
		echo "window.opener.getFormularios();";
		echo "window.close();";
		echo "</script>";
	}
?>
