var obj =
{
	codForm916:0,
	Interno:0,
	Parcela:0,
	Subparcela:0,
	Tipo:0,
    //---------------pared---------------//
	ParedA1:0,
	ParedA2:0,
	ParedA3:0,
	ParedA4:0,
	ParedB1:0,
	ParedB2:0,
    paredB3:0,
    ParedB4:0,
    ParedB5:0,
    ParedB6:0,
    ParedB7:0,
	observaciones:"",
	ParedC1:0,
	ParedC2:0,
	ParedC3:0,
	ParedEstado:"No Tiene",
	ParedReci:0,
    //---------------esqueleto---------------//
	EsqueA1:0,
	EsqueA2:0,
	EsqueA3:0,
	EsqueA4:0,
	EsqueB1:0,
	EsqueB2:0,
	EsqueB3:0,
	EsqueB4:0,
	EsqueB5:0,
	EsqueC1:0,
	EsqueC2:0,
	EsqueC3:0,
	EsqueEstado:"No Tiene",
	EsqueReci:0,
    //---------------Armadura---------------//
    ArmaA1:0,
    ArmaA2:0,
    ArmaA3:0,
    ArmaA4:0,
    ArmaB1:0,
    ArmaB2:0,
    ArmaB3:0,
    ArmaB4:0,
    ArmaB5:0,
    ArmaC1:0,
    ArmaC2:0,
    ArmaC3:0,
    ArmaEstado:"No Tiene",
    ArmaReci:0,
    //---------------techos---------------//
	TechoA1:0,
	TechoA2:0,
	TechoA3:0,
	TechoA4:0,
	TechoB1:0,
	TechoB2:0,
	TechoB3:0,
	TechoB4:0,
	TechoB5:0,
	TechoC1:0,
	TechoC2:0,
	TechoC3:0,
	TechoEstado:"No Tiene",
	TechoReci:0,
    //---------------revoques---------------//
	RevoqA1:0,
	RevoqA2:0,
	RevoqB1:0,
	RevoqB2:0,
	RevoqC1:0,
	RevoqEstado:"No Tiene",
	RevoqReci:0,
    //---------------pisos---------------//
	PisosA1:0,
	PisosA2:0,
	PisosA3:0,
	PisosA4:0,
	PisosB1:0,
	PisosB2:0,
	PisosB3:0,
	PisosC1:0,
	PisosEstado:"No Tiene",
	PisosReci:0,
    //---------------puerta de madera---------------//
	MadeA1:0,
	MadeA2:0,
	MadeB1:0,
	MadeC1:0,
	MadeEstado:"No Tiene",
	MadeReci:0,
    // ---------------puertas de metal---------------//
	MetaA1:0,
	MetaB1:0,
	MetaC1:0,
	MetaEstado:"No Tiene",
	MetaReci:0,
    //---------------Gas---------------//
	GasA1:0,
	GasA2:0,
	GasA3:0,
	GasA4:0,
	GasB1:0,
	GasB2:0,
	GasB3:0,
	GasC1:0,
	GasEstado:"No Tiene",
	GasReci:0,
    //---------------Luz---------------//
    LuzA1:0,
    LuzA2:0,
    LuzA3:0,
    LuzB1:0,
    LuzB2:0,
    LuzA3:0,
    LuzC1:0,
    LuzEstado:"No Tiene",
    LuzReci:0,
    //---------------Agua---------------//
    AguaA1:0,
    AguaA2:0,
    AguaA3:0,
    AguaA4:0,
    AguaA5:0,
    AguaB1:0,
    AguaB2:0,
    AguaB3:0,
    AguaC1:0,
    AguaEstado:"No Tiene",
    AguaReci:0,
	//---------------otros---------------//
	Cubierta:0,
	Data:0,
	Dia1:0,
	Dia:0,
	Data1:0,
	Estado:0,
	Rubrorural:0,
	Pagina:0,
	Destino:"",
	firmaprof:0
};
