<?php

	include ("sql/conexion.php");
  $idComunicado=$_GET["idComunicado"];
	$row = mysqli_fetch_array(mysqli_query($conexion,"SELECT * FROM comunicados where idComunicado='$idComunicado'"));

	$tipo = $row['tipo'];
	$nro1 = $row['nro1'];
	$nro2 = $row['nro2'];
	$nro3 = $row['nro3'];
	$apro = $row['apro'];
	$insc = $row['insc'];
	$desi = $row['desi'];
	$nomo = $row['nomo'];
	$nomd = $row['nomd'];
	$part = $row['part'];
	$obje = $row['obje'];
	$canp = $row['canp'];
	$rest = $row['rest'];
	$pat1 = $row['pat1'];
	$cir1 = $row['cir1'];
	$sec1 = $row['sec1'];
	$cha1 = $row['cha1'];
	$qui1 = $row['qui1'];
	$fra1 = $row['fra1'];
	$man1 = $row['man1'];
	$par1 = $row['par1'];
	$sup1 = $row['sup1'];
	$des1 = $row['des1'];
	$pat2 = $row['pat2'];
	$cir2 = $row['cir2'];
	$sec2 = $row['sec2'];
	$cha2 = $row['cha2'];
	$qui2 = $row['qui2'];
	$fra2 = $row['fra2'];
	$man2 = $row['man2'];
	$par2 = $row['par2'];
	$sup2 = $row['sup2'];
	$des2 = $row['des2'];
	$pat3 = $row['pat3'];
	$cir3 = $row['cir3'];
	$sec3 = $row['sec3'];
	$cha3 = $row['cha3'];
	$qui3 = $row['qui3'];
	$fra3 = $row['fra3'];
	$man3 = $row['man3'];
	$par3 = $row['par3'];
	$sup3 = $row['sup3'];
	$des3 = $row['des3'];
	$pat4 = $row['pat4'];
	$cir4 = $row['cir4'];
	$sec4 = $row['sec4'];
	$cha4 = $row['cha4'];
	$qui4 = $row['qui4'];
	$fra4 = $row['fra4'];
	$man4 = $row['man4'];
	$par4 = $row['par4'];
	$sup4 = $row['sup4'];
	$des4 = $row['des4'];
	$pat5 = $row['pat5'];
	$cir5 = $row['cir5'];
	$sec5 = $row['sec5'];
	$cha5 = $row['cha5'];
	$qui5 = $row['qui5'];
	$fra5 = $row['fra5'];
	$man5 = $row['man5'];
	$par5 = $row['par5'];
	$sup5 = $row['sup5'];
	$des5 = $row['des5'];
	$canc = $row['canc'];
	$rati = $row['rati'];
	$mostrarProf = $row['firmaprof'];

	?>
